services:
  - mongodb
language: node_js
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
node_js:
  - "4.4"
  - "5"
  - "6"
before_install: npm install -g grunt-cli
install: npm install && bower install
